export const FoodConstants = {
  FETCH_FOOD_REQUEST: "FETCH_FOOD_REQUEST",
  FETCH_FOOD_SUCCESS: "FETCH_FOOD_SUCCESS",
  FETCH_FOOD_FAIL: "FETCH_FOOD_FAIL",
  FETCH_FOOD_DETAIL_REQUEST: "FETCH_FOOD_DETAIL_REQUEST",
  FETCH_FOOD_DETAIL_SUCCESS: "FETCH_FOOD_DETAIL_SUCCESS",
  FETCH_FOOD_DETAIL_FAIL: "FETCH_FOOD_DETAIL_FAIL",
};
